# this also works great on osx, but I disabled osx to conserve Travis-CI resources.
language: python
group: travis_latest

git:
  depth: 3
  quiet: true

python:
- 3.6

os:
- linux

addons:
  apt:
    packages:
    - aspell

install:
- pip install -e .[tests,cov]

script:
- if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
  flake8;
  mypy . --ignore-missing-imports;
  fi

